#!/bin/sh

##############################################################################
# By default, change the specified user's uid and gid to match the user that
# owns the project directory and run a command as that user. If a ~/.ssh
# directory exists and it's not owned by root then switch and run as that user
# instead.
##############################################################################

stat_dir="/src"
if [ -d "/home/$1/.ssh" ] && [ "0" != "$(stat -c '%g' /home/$1/.ssh)" ] && [ "0" != "$(stat -c '%u' /home/$1/.ssh)" ]; then
    stat_dir="/home/$1/.ssh"
fi

groupmod -g $(stat -c '%g' $stat_dir) -o $1 > /dev/null 2>&1
usermod -u $(stat -c '%u' $stat_dir) -o $1 > /dev/null 2>&1
chown -R $1:$1 ~$1/ > /dev/null 2>&1
echo "running 'sudo -u $@'"
sudo -u $@
